openapi: 3.0.0
info:
  title: API de Carritos
  description: API para gestionar carritos de compras
  version: 1.0.0

paths:
  /carts/:
    post:
      summary: Crear un nuevo carrito
      description: Crea un nuevo carrito de compras vacío.
      responses:
        '201':
          description: Carrito creado con éxito
        '500':
          description: Error interno del servidor
      security:
        - cookieAuth: []

  /carts/:cid/product/:pid:
    post:
      summary: Agregar producto al carrito
      description: Agrega un producto al carrito de compras.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto agregado al carrito con éxito
        '400':
          description: Error de validación o usuario administrador
        '404':
          description: Carrito o producto no encontrado
        '500':
          description: Error interno del servidor
      security:
        - cookieAuth: []

  /carts/:cid:
    get:
      summary: Obtener carrito por ID
      description: Obtiene el carrito de compras por su ID.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        '200':
          description: Éxito
        '404':
          description: Carrito no encontrado
        '500':
          description: Error interno del servidor
      security:
        - cookieAuth: []

    delete:
      summary: Eliminar carrito por ID
      description: Elimina el carrito de compras por su ID.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        '200':
          description: Carrito eliminado con éxito
        '404':
          description: Carrito no encontrado
        '500':
          description: Error interno del servidor
      security:
        - cookieAuth: []

  /carts/:cid/products/:pid:
    delete:
      summary: Eliminar producto del carrito
      description: Elimina un producto del carrito de compras.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado del carrito con éxito
        '400':
          description: ID no válido
        '404':
          description: Producto o carrito no encontrado
        '500':
          description: Error interno del servidor
      security:
        - cookieAuth: []

  /carts/:cid/product/:pid/edit:
    put:
      summary: Editar cantidad de producto en el carrito
      description: Edita la cantidad de un producto en el carrito de compras.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
              required:
                - quantity
            example:
              quantity: 3
      responses:
        '200':
          description: Producto editado en el carrito con éxito
        '400':
          description: ID no válido o cantidad incorrecta
        '404':
          description: Producto o carrito no encontrado
        '500':
          description: Error interno del servidor
      security:
        - cookieAuth: []

  /carts/:cid/purchase:
    get:
      summary: Realizar compra del carrito
      description: Realiza la compra de los productos en el carrito.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        '200':
          description: Compra exitosa
        '400':
          description: Usuario no autenticado o no hay suficiente stock para algunos productos
        '404':
          description: Carrito no encontrado
        '500':
          description: Error interno del servidor

components:
  schemas:
    Cart:
      type: object
      properties:
        id:
          type: string
        products:
          type: array
          items:
            type: object
            properties:
              product:
                type: string
              quantity:
                type: integer
          example:
            - product: "6131e1983dce15f3a95bbec0"
              quantity: 2
            - product: "6131e1983dce15f3a95bbec1"
              quantity: 1
    Ticket:
      type: object
      properties:
        amount:
          type: integer
        purchaser:
          type: string
